[package]
name = "housecraft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
debug = 1

[dependencies]
anyhow = "1.0.69"
chrono = "0.4.23"
clap = { version = "4.1.8", features = ["derive"] }
comfy-table = "6.1.4"
console = "0.15.5"
csv = "1.2.1"
lazy_static = "1.4.0"
mimalloc = { version = "0.1.34", default-features = false }
num_cpus = "1.15.0"
rayon = "1.7.0"
serde = { version = "1.0.154", features = ["derive"] }
serde_json = "1.0.94"
stable-vec = "0.4.0"
